apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: casalinas83/first-app
        ports:
        - name: nodejs-port
          containerPort: 8080
