apiVersion: v1
kind: ReplicationController
metadata:
  name: scaling-first-app
spec:
  replicas: 2
  selector:
    app: scaling-first-app
  template:
    metadata:
      labels:
        app: scaling-first-app
    spec:
      containers:
      - name: first-app
        image: casalinas83/first-app
        ports:
        - name: nodejs-port
          containerPort: 8080
