apiVersion: v1
kind: Pod
metadata:
  name: first-app
  labels:
    app: first-app
spec:
  containers:
  - name: first-app
    image: casalinas83/first-app
    ports:
    - name: nodejs-port
      containerPort: 8080
